{% set name = "uglify-js" %}
{% set version = "3.14.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mishoo/UglifyJS2/archive/v{{ version }}.tar.gz
  sha256: 43de653dceff53ee7b3d4a360f8e9e42e9f075441b9506ba651a1885850d0ef5

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs

test:
  commands:
    - npm list -g uglify-js
    - uglifyjs --help
  requires:
    - nodejs

about:
  home: https://github.com/mishoo/UglifyJS2#readme
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: JavaScript parser / mangler / compressor / beautifier toolkit

extra:
  recipe-maintainers:
    - scopatz
